name: Update Dashboard Data

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for update'
        required: false
        default: 'Manual update'

  # Schedule - run every 6 hours
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Create credentials file
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: echo "$GOOGLE_CREDENTIALS" > credentials.json

      - name: Update data from Google Sheets
        env:
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          SHEET_NAME: ${{ secrets.SHEET_NAME }}
        run: node update_data.js

      - name: Commit and push if data changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add sample_data.js
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update dashboard data from Google Sheets" && git push) 